//
//  ExportJamInteractor.swift
//  SoundBoy
//
//  Created by Marlon Monroy on 10/26/17.
//  Copyright (c) 2017 DragLabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExportJamBusinessLogic
{
  func doSomething(request: ExportJam.Something.Request)
}

protocol ExportJamDataStore
{
  //var name: String { get set }
}

class ExportJamInteractor: ExportJamBusinessLogic, ExportJamDataStore
{
  var presenter: ExportJamPresentationLogic?
  var worker: ExportJamWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ExportJam.Something.Request)
  {
    worker = ExportJamWorker()
    worker?.doSomeWork()
    
    let response = ExportJam.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
