//
//  ExportJamPresenter.swift
//  SoundBoy
//
//  Created by Marlon Monroy on 10/26/17.
//  Copyright (c) 2017 DragLabs. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExportJamPresentationLogic
{
  func presentSomething(response: ExportJam.Something.Response)
}

class ExportJamPresenter: ExportJamPresentationLogic
{
  weak var viewController: ExportJamDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ExportJam.Something.Response)
  {
    let viewModel = ExportJam.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
